#!/usr/bin/with-contenv bash
# shellcheck shell=bash

EXITCODE=0

# BeastHost
if [ -z "${BEAST_HOST}" ]; then
  echo "ERROR: BEAST_HOST environment variable not set"
  EXITCODE=1
fi
# FR24_Key
if [ -z "${FR24_KEY}" ]; then
  echo "ERROR: FR24_KEY environment variable was not set"
  EXITCODE=1
fi

# Set up timezone
ln -snf /usr/share/zoneinfo/GMT /etc/localtime && echo "GMT" > /etc/timezone

exit $EXITCODE
