#!/usr/bin/with-contenv bash
# shellcheck shell=bash

EXITCODE=0
# Define bash colours
NOCOLOR='\e[0m'
#LIGHTRED='\e[1;31m'
YELLOW='\e[1;33m'
#CYAN='\e[0;36m'

# Set up timezone
if [ -z "${TZ}" ]; then
  echo "${YELLOW}WARNING: TZ environment variable not set${NOCOLOR}"
else
  ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime && echo "$TZ" > /etc/timezone
fi

exit $EXITCODE
