#!/usr/bin/with-contenv bash
# shellcheck shell=bash

EXITCODE=0
# Define bash colours
NOCOLOR='\e[0m'
#LIGHTRED='\e[1;31m'
YELLOW='\e[1;33m'
#CYAN='\e[0;36m'

# Set up timezone
ln -snf /usr/share/zoneinfo/GMT /etc/localtime && echo "GMT" > /etc/timezone


exit $EXITCODE
