name: Docker Build

on:
  push:
    branches:
      - develop

jobs:
  buildx:
    name: Test image build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-platform:
          - linux/amd64
          #- linux/arm64
          #- linux/arm/v6
          - linux/arm/v7
          #- linux/i386
    steps:
      # Checkout Code
      - name: Checkout
        uses: actions/checkout@v2
      # Set Up QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # Set up buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # Build Image 
      - name: Test Build ${{ matrix.docker-platform }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.docker-platform }}
          no-cache: true
          push: false
          load: true
          tags: myimage:latest
      # Test image
      - name: Inspect
        run: |
          docker image inspect myimage:latest
          docker run -d -e BEAST_HOST='192.168.1.1' -e FR24_MAIL='mel@mel.com' -e LATITUDE='46.0' -e LONGITUDE='4.0' -e ALTITUDE='590' --name test myimage:latest
          sleep 20
          docker logs test
          docker rm --force test
